version: 0.2
env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing
      - npm --prefix "$CODEBUILD_SRC_DIR" install

  pre_build:
    commands:
      - npm --prefix "$CODEBUILD_SRC_DIR" run clean

  build:
    commands:
      - echo Build started at `date`
      - npm --prefix "$CODEBUILD_SRC_DIR" run build
      - echo Build completed at `date`

artifacts:
  files:
    - build/**/*
  name: aws-codepipeline-monitor-$CODEBUILD_BUILD_NUMBER
  discard-paths: no
