/**
 * The CodePipelineEvent describes the properties available by all events that are generated during the life-cycle of
 * a code pipeline execution.
 *
 * https://docs.aws.amazon.com/codepipeline/latest/userguide/detect-state-changes-cloudwatch-events.html
 */
export type CodePipelineEvent = {
  detail: {
    pipeline: string;
    "execution-id": string;
    version: 16.0;
  };
  account: string;
  region: string;
  source: string;
  time: string;
  notificationRuleArn: string;
  resources: string[];
};

/**
 * Information generated by an AWS Code Pipeline Execution Event.
 * https://docs.aws.amazon.com/codepipeline/latest/userguide/detect-state-changes-cloudwatch-events.html
 */
export type CodePipelineExecutionEvent = CodePipelineEvent & {
  detailType: "CodePipeline Pipeline Execution State Change";
  detail: {
    "execution-trigger"?: {
      "trigger-type": "Webhook" | "StartPipelineExecution";
      "trigger-detail": string;
    };
    state: "STARTED" | "SUCCEEDED" | "FAILED";
  };
  additionalAttributes: {
    sourceActions?: any[];
    failedActionCount?: number;
    failedActions?: CodePipelineFailedAction[];
    failedStage?: string;
  };
};

type CodePipelineFailedAction = {
  action: string;
  additionalInformation: string;
};

/**
 * Information generated by an AWS Code Pipeline Stage Event.
 * https://docs.aws.amazon.com/codepipeline/latest/userguide/detect-state-changes-cloudwatch-events.html
 */
export type CodePipelineStageEvent = CodePipelineEvent & {
  detailType: "CodePipeline Stage Execution State Change";
  detail: {
    state: "STARTED" | "SUCCEEDED" | "FAILED";
    stage: string;
  };
  additionalAttributes: {
    sourceActions?: any[];
    failedActionCount?: number;
    failedActions?: CodePipelineFailedAction[];
  };
};

/**
 * Information about an AWS CodePipeline Action Type.
 * https://docs.aws.amazon.com/codepipeline/latest/APIReference/API_ActionType.html
 */
type CodePipelineActionType = {
  owner: "AWS";
  provider: string;
  category: string;
  version: "1";
};

/**
 * Describes properties available for a CodePipeline Artificat.
 * https://docs.aws.amazon.com/codepipeline/latest/APIReference/API_Artifact.html
 */
type CodePipeLineArtifact = {
  name: string;
  s3location: {
    bucket: string;
    key: string;
  };
};

/**
 * Information generated by an AWS Code Pipeline Action Event.
 *
 * https://docs.aws.amazon.com/codepipeline/latest/userguide/detect-state-changes-cloudwatch-events.html
 */
export type CodePipelineActionEvent = CodePipelineEvent & {
  detailType: "CodePipeline Action Execution State Change";
  detail: {
    "execution-result"?: {
      "external-execution-url": string;
      "external-execution-id": string;
      "external-execution-summary"?: string;
      "error-code"?: string;
    };
    "input-artifacts"?: CodePipeLineArtifact[];
    "output-artifacts"?: CodePipeLineArtifact[];
    state: "STARTED" | "SUCCEEDED" | "FAILED";
    action: "Source" | "Build" | string;
    stage: string;
    region: string;
    type: CodePipelineActionType;
  };
  additionalAttributes: {
    sourceActions?: any[];
    additionalInformation?: string;
    externalEntityLink?: string;
    customData?: string;
  };
};
